unbind C-b
set -g prefix \\
bind \\ send-prefix
set -g default-command "bash"
set -g base-index 1
set -g pane-base-index 1
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded successfully! ✅"
unbind C
bind C command-prompt -p "New session name:" "new-session -s '%%'" #bear in mind the max name char limit as of right now without affecting spacing is 7
unbind [
unbind ]
bind [ switch-client -p #previous session
bind ] switch-client -n #next session
bind s split-window -v
bind S split-window -h
bind o last-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#'rename' keytable 
bind n switch-client -T rename
bind -T rename p command-prompt "select-pane -T '%%'"
bind -T rename w command-prompt "rename-window '%%'"
bind -T rename s command-prompt "rename-session '%%'"

#'window-swap' keytable
unbind >
unbind <
bind > switch-client -T window-swap
bind < switch-client -T window-swap
bind -T window-swap 1 swap-window -t 1
bind -T window-swap 2 swap-window -t 2
bind -T window-swap 3 swap-window -t 3
bind -T window-swap 4 swap-window -t 4
bind -T window-swap 5 swap-window -t 5
bind -T window-swap 6 swap-window -t 6
bind -T window-swap 7 swap-window -t 7
bind -T window-swap 8 swap-window -t 8
bind -T window-swap 9 swap-window -t 9

bind X detach-client
bind Q confirm-before -p "Kill tmux session #S? (y/n)" kill-session

#overwrites
bind x kill-pane #default is x, but with a prompt to confirm. I don't want this, so I overwrote the default key binding
bind c command-prompt -p "New window name:" "new-window -n '%%'" #prompts user to name new window upon creation
