unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
bind s split-window -v
bind S split-window -h
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#'rename' keytable 
bind n switch-client -T rename
bind -T rename p command-prompt "select-pane -T '%%'"
bind -T rename w command-prompt "rename-window '%%'"

bind ? run-shell "bash -c 'man tmux | less +90; exit'"
bind x kill-pane #default is x, but with a prompt to confirm. I don't want this, so I overwrote the default key binding
bind X confirm-before -p "Kill the entire tmux session? (y/n)" kill-session
